### PR TITLE
Allow routes to be filtered by hosts

### PR DESCRIPTION
**Pull request by zimmpatrick**
Allow routes to be filtered by hosts, or allow a route to match only a host value.

For example 'twitter://timeline' would be matched with a route of '[timeline]'
http://wiki.akosma.com/IPhone_URL_Schemes#Twitter

### CODE REVIEW

**Comment by wessmith** [comment]
@zimmpatrick We definitely considered matching on host, but then stayed more toward the AppLinks model of using the host to define the deep link “standard” being used. We were also trying to support any casual use case, but obviously didn't cover this bit well. 

I'm not so sure about introducing seemingly arbitrary `[]` characters to define the host format. This would complicate using the route format as a regex pattern down the road. It makes me think that we should enforce the leading `/` of the path in order to define a path format to be matched. For example, `router[@"timeline"] = ^{}` would match `twitter://timeline`, but `router[@"/timeline"] = ^{}` would not.  Conversely, `router[@"/timeline"] = ^{}` would match a URL of `twitter://dpl.com/timeline` but  `router[@"timeline"] = ^{}` would not.

We actually have a standard to base this enforcement on:
> Per RFC 3986, the leading slash after the authority (host name and port) portion is treated as part of the path. For example, in the URL http://www.example.com/index.html, the path is /index.html.

**Comment by zimmpatrick** [comment]
Wes, good points.  I used the [ ] format because those characters are not allowed in URLs and keeps it backwards compatible.

I'm working on updating an existing app that already has existing URLs I want to keep compatibility with.  

Wouldn't the leading path convention would break existing apps using the framework?

**Comment by wessmith** [comment]
@zimmpatrick It would potentially break existing apps. I'm not terribly concerned about this as we're still pre 1.0. We'll just have to call it out in the readme.

**Comment by wessmith** [comment]
@zimmpatrick Haven't forgotten about this, just having a busy week :smile:

**Comment by jrwagz** [comment]
We'd also like to use this, and right now the lack of support for matching the host is a deal breaker...

**Comment by chrismaddern** [comment]
Expect host support within the next few days. There are a few other considerations outside this P/R, but will be in place soon!

**Comment by zimmpatrick** [comment]
Any updates?

**Comment by chrismaddern** [comment]
Hey @zimmpatrick -- we're preparing to push some changes including your work. Could you sign our Contributor License Agreement as your commits are in there :smile: 

https://docs.google.com/forms/d/1WHFWnzz5OL8c9o49KgpgyERzQUQajX5p8_80YLCghds/viewform?usp=send_form

**Pull request merged**
