### PR TITLE
Add object subscripting to links.

### PR DESCRIPTION
**Pull request by chrismaddern**

### CODE REVIEW

**Comment by chrismaddern** [comment]
Hey @getaaron - before we release this to 0.2.1, could you sign our CLA? Sorry for the inconvenience but it's a necessity when maintaining open source code as a company :)

https://docs.google.com/forms/d/1WHFWnzz5OL8c9o49KgpgyERzQUQajX5p8_80YLCghds/viewform?usp=send_form

**Comment by getaaron** [comment]
@chrismaddern Done.

**Comment by chrismaddern** [comment]
Awesome! Thanks @getaaron!

I actually love this now :D

**Comment by getaaron** [comment]
@chrismaddern  You also need to reflect the change in `DPLDeepLink.h`. The comment still describes the old behavior.

**Comment by chrismaddern** [comment]
Great catch! Thanks!

**Comment by getaaron** [comment]
Glad you came around haha :)

**Pull request merged**
